// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BusinessFormController from "./business_form_controller"
application.register("business-form", BusinessFormController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import RemovalsController from "./removals_controller"
application.register("removals", RemovalsController)
